### ISSUE TITLE
Missing Config file?

### ISSUE THREAD

**Issue by Infamuzunknow** [FordPIU/FiveM-QBCore-CryptoMining#1]
in the description it says to can modify the mining rates etc... in the config file but that does not seem to be in the release

**Comment by Cal-Caleb** [comment]
If you look under Server/EnsureJsons.lua, you'll find the configuration in there.
It's there because of the way i setup the json files and selves, so no 2 people can buy the same shelf.

I'll add it to the Readme in a bit, as to where the config is.
