### ISSUE TITLE
calling for resource npwd_crypto export

### ISSUE THREAD

**Issue by Soldierofthelam** [FordPIU/FiveM-QBCore-CryptoMining#2]
SCRIPT ERROR: @CryptoMining/Server/Difficulty.lua:18: No such export GetCryptoValue in resource npwd_crypto

I'm using the renewed-phone with the 4 cryptos
https://github.com/Renewed-Scripts/qb-phone

how would I change this? Under difficulty.lua?

Citizen.CreateThread(function()
    Wait(5000)
    while true do
        Wait(10000)
        local Worth = exports["npwd_crypto"]:GetCryptoValue()

        if Worth ~= nil then
            Difficulty = ((Worth * GetPriceDivider()) * 0.0005) + (GetRandomFloatInRange(0.1, 1.0) / 10)
        end

        TriggerClientEvent("CQBMININGV2:UpdateDifficulty", -1, Difficulty)
    end
end)

**Comment by Cal-Caleb** [comment]
Hey, sorry for the late reply;

Without some code changes, this only supports single coin, so you would want to pick a single coin and swap the export over to that.
Also be sure to change the payout function as well.

**Comment by Soldierofthelam** [comment]
The renewed phone with the 4 crypto choices has the names abbreviated with 4 letters I tried changing each one at a time to them but I think your right Imma have to change some code to make it work renewed phone also has a funny way to install it to function as well you gotta change a line of code then change it back for certain functions to work like a manual on off switch for code it gets annoying with the phone script also when you add in more jobs to the management. I'll have to fiddle with it more I find your crypto mining scripting unique and different than most and thing it would blend well with my test server.
